### ISSUE TITLE
linux - Perfect Dark v1.1 hangs at expansion pack found screen

### ISSUE THREAD

**Issue by 7oxicshadow** [loganmc10/GLupeN64#104]
When loading Perfect Dark it hangs at the screen with purple text saying expansion pack found.

I cant seem to see any parameters for turning the expansion pack on an off.

**Comment by loganmc10** [comment]
hm I can reproduce this, it doesn't have anything to do with the expansion pack, that screen just happens to mention the expansion pack, I'll need to look into this a bit

**Comment by loganmc10** [comment]
So it turns out this is because of this line in mupen64plus.ini
```
SaveType=Eeprom 16KB
```
Removing that entry in the Perfect Dark section makes the game work. I need to test this in mupen64plus to see if it is happening there as well.

**Comment by loganmc10** [comment]
This seems to be related to having the controller paks set to "memory".

If you set them to "none" (glupen64-pak1 - glupen64-pak4 in the core options) it should launch.

I haven't tried "rumble". I've changed the default to "none" which is the same as mupen64plus-libretro

**Comment by 7oxicshadow** [comment]
Good catch. I can confirm that it works for me aswell,

I started to dig a little deeper and it turns out that pak4 is the one causing the issue. Controllers 1 to 3 can have memory packs with no problems.

**Comment by loganmc10** [comment]
huh, yep I can confirm the same thing. Very interesting, I never tested that with mupen64plus, so this could be (and probably is) a bug with mupen64plus, or it could even be a bug that existed in Perfect Dark itself, since the emulator never actually crashes, the game just seems to pause there, the frame count keeps going up. I doubt a lot of people ever had 4 controllers each with a memory pack plugged in at once.

Anyway I think settings the default controller setup to "none" will probably have to suffice, even if they set controller 1 to "memory", which they might, they still won't run into this bug.

**Comment by 7oxicshadow** [comment]
Yeh I agree. I believe this bug is solved so I will close this issue. If you come across anything more of interest just re-open.

Thanks.
