### ISSUE TITLE
Zelda: Majora's Mask: Rendering bug

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#12]
OS: `Slackware64-current`
`mesa-3a2e67b_2016.07.23_master-x86_64-1_git`
`RetroArch-1.3.6-x86_64-1_SBo`

In the area with the first deku flower where the previous rendering issue presented itself (Issue: https://github.com/loganmc10/GLupeN64/issues/2) I found if I load a savestate it will still look broken, but after walking around a little bit it will improve. However it will repeat if I make another savestate.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-02-085811_1680x1050_scrot.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-02-090045_1680x1050_scrot.png)
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/mupen64plus/2016-08-02-090056_1680x1050_scrot.png)

mupen64plus-libretro experiences similar when using the changes from your glsm.c.
https://github.com/libretro/mupen64plus-libretro/issues/344

**Comment by loganmc10** [comment]
Can you post a save state for me?

**Comment by orbea** [comment]
Savestate: http://ks392457.kimsufi.com/orbea/stuff/games/n64/sstates/Legend%20of%20Zelda,%20The%20-%20Majora's%20Mask%20(U)%20%5b!%5d.state

`2a0a8acb61538235bc1094d297fb6556  Legend of Zelda, The - Majora's Mask (U) [!].z64`

**Comment by loganmc10** [comment]
Sorry I haven't had a chance to test this yet, but can you try it with the latest master when you get a chance?

**Comment by orbea** [comment]
I can't start the game anymore, it freezes on a blackscreen where its notifying that my keyboard is not autoconfigured (RA thinks its a gamepad...).

**Comment by orbea** [comment]
Nvm, it was a problem with probably xorg or maybe nouveau which didn't resume from suspend properly causing at least some gl programs to freeze my x session. Rebooting worked around it for now...

Anyways, you fixed the issue, thanks! :)

What do you think about incorporating some of your fixes into mupen64plus-libretro?
Here are some issues you don't seem to suffer.
https://github.com/libretro/mupen64plus-libretro/issues/341
https://github.com/libretro/mupen64plus-libretro/issues/344
https://github.com/libretro/mupen64plus-libretro/issues/342

**Comment by loganmc10** [comment]
Well a few of those issues could be fixed by adding this:

https://github.com/loganmc10/GLupeN64/blob/master/custom/glsm/glsm.c#L2009-L2017

to glsm.c in mupen64plus-libretro (along with the associated code to track the state changes):
https://github.com/loganmc10/GLupeN64/blob/master/custom/glsm/glsm.c#L35-L43
https://github.com/loganmc10/GLupeN64/blob/master/custom/glsm/glsm.c#L1284-L1292

Some of those issues could be because mupen64plus-libretro uses an older and modified version of GLideN64. The whole point of this project is to be able to use the latest and greatest GLideN64 and mupen64plus code. mupen64plus-libretro has a lot of customization, even for GLideN64, so I can't spend the time to track down what might be cause certain issues.

Anyway, so yes, the glsm could be incorporated into mupen64plus-libretro, although I believe twinaphex has plans to somehow "merge" all the HLE graphics plugins into 1 soon (Rice, gln64, gliden64 etc..), so it might look pretty different anyway.

**Comment by orbea** [comment]
I can confirm your changes to glsm.c at least fix the rendering issue with Majora's Mask for mupen64plus-libretro, the other issues persist though.

I also sent a PR. https://github.com/libretro/mupen64plus-libretro/pull/370
