### ISSUE TITLE
GLideN64 Error: Depth Compare and Depth Based Fog

### ISSUE THREAD

**Issue by LEGOAnimal22** [loganmc10/GLupeN64#25]
When I run this emulator on my Raspberry Pi 2, it generates a file called `gliden64.log` in the /home/pi directory. The file contains this message:
`N64 depth compare and depth based fog will not work without Image Textures support provided in OpenGL >= 4.3 or GLES >= 3.1`

**Comment by loganmc10** [comment]
This happens on regular mupen64plus as well, it is more of an "announcement" than an error, just telling you that those features won't work because the Raspberry Pi only supports GLES2

https://github.com/gonetz/GLideN64/blob/master/src/OpenGL.cpp#L1886

It should probably be LOG_VERBOSE instead of LOG_WARNING, but that is a GLideN64 thing

**Comment by LEGOAnimal22** [comment]
Oh, okay. I'll close this then.
