### ISSUE TITLE
x86_64 support only?

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#40]
Does GLupeN64 plan to support x86_64 only? I tried to build it in a 32-bit chroot and got:
`mupen64plus-core/src/r4300/new_dynarec/x86/linkage_x86.asm:1: *** missing rule before recipe.  Stop.`

If 32-bit is not supported, can that be added somewhere to the README? :)

**Comment by loganmc10** [comment]
32-bit should be supported, but I don't really have a way to test it. I believe the issue you're running into is just a Makefile problem, because the x86 asm file ends in .asm instead of .S like the rest.

You can try changing the line in ```Makefile```

```
OBJECTS     += $(SOURCES_CXX:.cpp=.o) $(SOURCES_C:.c=.o) $(SOURCES_ASM:.S=.o)
```

to read
```
OBJECTS     += $(SOURCES_CXX:.cpp=.o) $(SOURCES_C:.c=.o) $(SOURCES_ASM:.S=.o) $(SOURCES_ASM:.arm=.o)
```

I'm not really a Makefile expert, so that might not be the correct syntax. You might have to play around with it a bit, if you find one that works let me know and I'll commit the change.

**Comment by loganmc10** [comment]
32-bit should be supported, but I don't really have a way to test it. I believe the issue you're running into is just a Makefile problem, because the x86 asm file ends in .asm instead of .S like the rest.

You can try changing the line in ```Makefile```

```
OBJECTS     += $(SOURCES_CXX:.cpp=.o) $(SOURCES_C:.c=.o) $(SOURCES_ASM:.S=.o)
```

to read
```
OBJECTS     += $(SOURCES_CXX:.cpp=.o) $(SOURCES_C:.c=.o) $(SOURCES_ASM:.S=.o) $(SOURCES_ASM:.arm=.o)
```

I'm not really a Makefile expert, so that might not be the correct syntax. You might have to play around with it a bit, if you find one that works let me know and I'll commit the change.

**Comment by orbea** [comment]
No difference. Comparing with the mupen64plus-core Makefile I tried to add a rule for .asm, but still no difference.
https://github.com/mupen64plus/mupen64plus-core/blob/master/projects/unix/Makefile

**Comment by loganmc10** [comment]
OK, I'll get this working tomorrow

**Comment by loganmc10** [comment]
Should hopefully be fixed now, https://github.com/loganmc10/GLupeN64/commit/3b73e6ee5545ddb7f569d64a4a5514b394d50598

**Comment by orbea** [comment]
Thanks, it builds now.
