### ISSUE TITLE
(emscripten) Super Smash Bros - Missing textures

### ISSUE THREAD

**Issue by orbea** [loganmc10/GLupeN64#62]
OS: `Slackware64-current`
`mozilla-firefox-49.0-x86_64`
`PaleMoon-26.4.1-x86_64`

Super Smash Bros has various textures which will be missing and appear as black, this seems to only affect emscripten at least with mozilla based browsers.

![1](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-09-24-175529_1680x1050_scrot.png)
![2](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-09-24-173143_1680x1050_scrot.png)
![3](http://ks392457.kimsufi.com/orbea/stuff/pics/scrots/libretro/glupen64/2016-09-24-173955_1680x1050_scrot.png)

**Comment by loganmc10** [comment]
It's kind of a miracle that it works at all lol but I'll look into it. Does the controller work for you? I couldn't get Z or start to work it seemed

**Comment by orbea** [comment]
Yea, its surprising that it works at all.

The controller works with firefox, at least partially. No R2 or dpad, L2 is bound to incorrectly to jump and L3 is start. In palemoon it does not even see the controller.

**Comment by loganmc10** [comment]
I can reproduce this in Chrome. Framebuffer Emulation doesn't work in emscripten either (it complains about a wrong texture format or something, so it's disabled by default).

Right now with emscripten the EGL graphics context doesn't work, it uses SDL2 to provide Open GL ES 2. I'm going to wait until they get EGL working with emscripten to look into this more, since that might solve the problem. EGL is the same thing that is used with Android so it's more thoroughly tested, I don't think the SDL2 context gets used much.

**Comment by orbea** [comment]
That makes sense, thanks for looking into this.

**Comment by loganmc10** [comment]
I just tested with the EGL context driver and it has the same issue. I'm not really sure what to do, I don't see any errors in the Chrome developer console related to this, so I'm just going to leave it for now.

WebGL is supposed to support all the same features as OpenGL ES 2, so I'm not sure why it works on Android (and Desktop set to GLES2 mode), but not emscripten. I'm not sure if it's a bug with emscripten, WebGL, or what, I'm just going to leave it, since I don't have any experience with WebGL/emscripten really, but I'll leave this open in case anyone wants to tackle this.

**Comment by loganmc10** [comment]
I've decided to remove support for emscripten. It makes the code more complicated and it has issues like this. It also doesn't perform as well as I hoped, so it's not really usable in my view. If someone has a computer powerful enough to run this in a browser, then they probably have a computer that can install RetroArch.

**Comment by orbea** [comment]
Fair enough.
