### ISSUE TITLE
Diddy Kong Racing Crash

### ISSUE THREAD

**Issue by Awakened0** [loganmc10/GLupeN64#89]
Using the latest Windows build from your buildbot. Backtrace: http://hastebin.com/dekapuqadu.coffeescript

There's also a gliden64.log file in RetroArch\ that says:
> [GLideN64]: error - unknown ucode!!!
> [GLideN64]: error - unknown ucode!!!
> [GLideN64]: error - unknown ucode!!!

**Comment by loganmc10** [comment]
hm this is because I switched to xxHash for the CRC calculations. Basically a faster way to load textures.

Unfortunately GLideN64 has a system that checks microcodes based on a specific CRC algorithm, so it doesn't find a match. I'll probably need to send a pull request to GLideN64 to properly fix this with xxHash.

**Comment by loganmc10** [comment]
OK I opened a pull request with GLideN64 (https://github.com/gonetz/GLideN64/pull/1202), if that gets merged then I will be able to solve this problem. If not I will have to go back to the regular CRC calculations that happen with GLideN64

**Comment by loganmc10** [comment]
Should be fixed by da53b28dc18e813baeb4fcca2b17c83bc7f78b32
